import { app } from "electron";
import { join, dirname } from "path";
import { existsSync, mkdirSync, writeFileSync, chmodSync, unlinkSync } from "fs";
import { spawnSync } from "child_process";
import { Game } from "../../shared/types";
import { createLogger } from "../util/logger";

const log = createLogger("info");

function getScriptsDir(): string {
  return join(app.getPath("userData"), "desktop-scripts");
}

function getDesktopFilePath(gameId: string): string {
  const safeId = gameId.replace(/[^a-zA-Z0-9_-]/g, "_");
  return join(
    app.getPath("home"),
    ".local",
    "share",
    "applications",
    `ember-game-${safeId}.desktop`,
  );
}

function getScriptPath(gameId: string): string {
  const safeId = gameId.replace(/[^a-zA-Z0-9_-]/g, "_");
  return join(getScriptsDir(), `launch-${safeId}.sh`);
}

function escapeDesktopValue(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/\n/g, "\\n");
}

export function hasDesktopEntry(gameId: string): boolean {
  return existsSync(getDesktopFilePath(gameId));
}

export function removeDesktopEntry(gameId: string): void {
  const scriptPath = getScriptPath(gameId);
  const desktopPath = getDesktopFilePath(gameId);
  try {
    unlinkSync(scriptPath);
  } catch {
    /* ignore */
  }
  try {
    unlinkSync(desktopPath);
  } catch {
    /* ignore */
  }
}

function findProjectRoot(): string {
  let dir = __dirname;
  while (dir !== dirname(dir)) {
    if (existsSync(join(dir, "package.json"))) {
      return dir;
    }
    dir = dirname(dir);
  }
  return app.getAppPath();
}

function findPackageManager(): string | null {
  try {
    const bun = spawnSync("which", ["bun"], { encoding: "utf8" });
    if (bun.status === 0) return bun.stdout.trim();
  } catch { /* ignore */ }
  try {
    const npm = spawnSync("which", ["npm"], { encoding: "utf8" });
    if (npm.status === 0) return npm.stdout.trim();
  } catch { /* ignore */ }
  return null;
}

export function createDesktopEntry(game: Game): void {
  if (process.platform !== "linux") {
    log.warn("desktop-entry", "Desktop entries are only supported on Linux");
    return;
  }

  const scriptsDir = getScriptsDir();
  if (!existsSync(scriptsDir)) {
    mkdirSync(scriptsDir, { recursive: true });
  }

  const scriptPath = getScriptPath(game.id);
  const desktopPath = getDesktopFilePath(game.id);

  let scriptContent: string;

  if (app.isPackaged) {
    const emberBinary = process.execPath;
    scriptContent = `#!/bin/bash
# Auto-generated by Ember for "${game.title.replace(/"/g, '\\"')}"
cd "${dirname(emberBinary).replace(/"/g, '\\"')}"
"${emberBinary}" --launch-game="${game.id.replace(/"/g, '\\"')}"
`;
  } else {
    const pm = findPackageManager();
    const projectRoot = findProjectRoot();
    if (!pm) {
      log.warn("desktop-entry", "Cannot create desktop entry in dev mode: bun/npm not found in PATH");
      return;
    }
    scriptContent = `#!/bin/bash\n# Auto-generated by Ember for "${game.title.replace(/"/g, '\\"')}"\ncd "${projectRoot.replace(/"/g, '\\"')}"\n"${pm}" run dev -- --launch-game="${game.id.replace(/"/g, '\\"')}"\n`;
  }

  writeFileSync(scriptPath, scriptContent, { mode: 0o755 });
  chmodSync(scriptPath, 0o755);

  // Try to resolve an icon path
  let iconPath = "";
  if (game.coverUrl) {
    if (game.coverUrl.startsWith("/")) {
      iconPath = game.coverUrl;
    } else if (game.coverUrl.startsWith("ember://media/")) {
      iconPath = game.coverUrl.slice("ember://media/".length);
    }
  }

  const desktopContent = `[Desktop Entry]
Name=${escapeDesktopValue(game.title)}
Comment=Launch ${escapeDesktopValue(game.title)} via Ember
Exec=${escapeDesktopValue(scriptPath)}
Type=Application
Terminal=false
Categories=Game;
Icon=${escapeDesktopValue(iconPath || "applications-games")}
`;

  writeFileSync(desktopPath, desktopContent);

  // Update desktop database
  try {
    const appsDir = join(app.getPath("home"), ".local", "share", "applications");
    spawnSync("update-desktop-database", [appsDir], { stdio: "ignore" });
  } catch {
    // ignore - desktop database may not be available
  }

  log.info("desktop-entry", `Created desktop entry for "${game.title}" at ${desktopPath}`);
}
