export const IPC_CHANNELS = {
  settings: {
    get: "settings:get",
    set: "settings:set",
  },
  app: {
    fullscreen: "app:fullscreen",
    quit: "app:quit",
    restart: "app:restart",
    xdgDefaults: "app:xdg-defaults",
  },
  games: {
    scan: "games:scan",
    list: "games:list",
    launch: "games:launch",
    favorite: "games:favorite",
    tag: "games:tag",
    hide: "games:hide",
    metadata: "games:metadata",
    loadThumbnail: "games:loadThumbnail",
    regenerateThumbnail: "games:regenerateThumbnail",
    emulatorConfig: {
      get: "games:emulatorConfig:get",
      set: "games:emulatorConfig:set",
    },
    playTime: {
      start: "games:playTime:start",
      stop: "games:playTime:stop",
    },
  },
  movies: {
    scan: "movies:scan",
    list: "movies:list",
    launch: "movies:launch",
    favorite: "movies:favorite",
    tag: "movies:tag",
    hide: "movies:hide",
    progressSet: "movies:progress:set",
    metadata: "movies:metadata",
    regenerateThumbnail: "movies:regenerateThumbnail",
  },
  music: {
    scan: "music:scan",
    list: "music:list",
    launch: "music:launch",
    favorite: "music:favorite",
    tag: "music:tag",
    writeTags: "music:writeTags",
    hide: "music:hide",
    searchCoverArt: "music:searchCoverArt",
    pickCoverImage: "music:pickCoverImage",
    loadThumbnail: "music:loadThumbnail",
    artistThumbnail: "music:artistThumbnail",
    enrich: "music:enrich",
    enrichBatch: "music:enrichBatch",
    setLastPlayed: "music:lastPlayed",
    reorganizePreview: "music:reorganizePreview",
    reorganize: "music:reorganize",
  },
  tv: {
    scan: "tv:scan",
    list: "tv:list",
    launch: "tv:launch",
    favorite: "tv:favorite",
    tag: "tv:tag",
    hide: "tv:hide",
    metadata: "tv:metadata",
    regenerateThumbnail: "tv:regenerateThumbnail",
  },
  input: {
    devices: "input:devices",
    mappings: {
      get: "input:mappings:get",
      set: "input:mappings:set",
      reset: "input:mappings:reset",
    },
    event: "input:event",
    deviceConnected: "input:device-connected",
    deviceDisconnected: "input:device-disconnected",
  },
  plugins: {
    list: "plugins:list",
    reload: "plugins:reload",
  },
  db: {
    clear: "db:clear",
    clearAll: "db:clear-all",
  },
  dialog: {
    openDirectory: "dialog:open-directory",
    openFile: "dialog:open-file",
  },
  shell: {
    openPath: "shell:openPath",
    showItemInFolder: "shell:showItemInFolder",
  },
  files: {
    read: "files:read",
  },
  flashFilters: {
    list: "flash-filters:list",
    openDir: "flash-filters:open-dir",
  },
  scan: {
    progress: "scan:progress",
  },
  collections: {
    list: "collections:list",
    get: "collections:get",
    create: "collections:create",
    update: "collections:update",
    delete: "collections:delete",
    items: {
      add: "collections:items:add",
      remove: "collections:items:remove",
      list: "collections:items:list",
    },
    smartEvaluate: "collections:smart:evaluate",
  },
  playlist: {
    list: "playlist:list",
    create: "playlist:create",
    update: "playlist:update",
    delete: "playlist:delete",
    addTracks: "playlist:addTracks",
    removeTracks: "playlist:removeTracks",
    reorder: "playlist:reorder",
  },
  streaming: {
    list: "streaming:list",
    add: "streaming:add",
    update: "streaming:update",
    delete: "streaming:delete",
    setEnabled: "streaming:setEnabled",
    detectDesktopApp: "streaming:detectDesktopApp",
    launch: "streaming:launch",
    frontpage: {
      report: "streaming:frontpage:report",
      list: "streaming:frontpage:list",
      listAll: "streaming:frontpage:listAll",
      clear: "streaming:frontpage:clear",
    },
    usage: {
      start: "streaming:usage:start",
      stop: "streaming:usage:stop",
    },
    adapter: {
      search: "streaming:adapter:search",
      play: "streaming:adapter:play",
      pause: "streaming:adapter:pause",
      next: "streaming:adapter:next",
      previous: "streaming:adapter:previous",
      currentlyPlaying: "streaming:adapter:currentlyPlaying",
      getDevices: "streaming:adapter:getDevices",
      authenticate: "streaming:adapter:authenticate",
      disconnect: "streaming:adapter:disconnect",
      getTrack: "streaming:adapter:getTrack",
      getAlbum: "streaming:adapter:getAlbum",
      getPlaylist: "streaming:adapter:getPlaylist",
    },
    mediaKeys: "streaming:mediaKeys",
  },
  packages: {
    list: "packages:list",
    search: "packages:search",
    install: "packages:install",
    uninstall: "packages:uninstall",
    pin: "packages:pin",
    setAutoUpdate: "packages:setAutoUpdate",
    checkUpdates: "packages:checkUpdates",
    progress: "packages:progress",
    aptPassword: "packages:apt:password",
  },
  overlay: {
    toggle: "overlay:toggle",
    show: "overlay:show",
    hide: "overlay:hide",
    close: "overlay:close",
    getGame: "overlay:getGame",
    stopGame: "overlay:stopGame",
    pauseGame: "overlay:pauseGame",
    resumeGame: "overlay:resumeGame",
    isPaused: "overlay:isPaused",
    state: "overlay:state",
    processStats: "overlay:processStats",
  },
  devtools: {
    isOpen: "devtools:is-open",
    changed: "devtools:changed",
  },
} as const;
